### ISSUE TITLE
Unable to install b2evolution in Ubuntu 22.04

### ISSUE THREAD

**Issue by inscara** [b2evolution/b2evolution#119]
When trying to install manually in a local machine the installer crashes with the following message:

```
Fatal error: Uncaught mysqli_sql_exception: Table 'b2evolution.evo_settings' doesn't exist in /var/www/html/b2evolution/inc/_core/model/db/_db.class.php:975 Stack trace: #0 /var/www/html/b2evolution/inc/_core/model/db/_db.class.php(975): mysqli->query() #1 /var/www/html/b2evolution/inc/_core/model/db/_db.class.php(1240): DB->query() #2 /var/www/html/b2evolution/install/_functions_install.php(436): DB->get_results() #3 /var/www/html/b2evolution/install/_functions_install.php(380): db_col_exists() #4 /var/www/html/b2evolution/install/index.php(647): get_db_version() #5 {main} thrown in /var/www/html/b2evolution/inc/_core/model/db/_db.class.php on line 975
```

The database `b2evolution` was created with mysql client.

**Comment by Metztli** [comment]
Niltze,

It is likely because b2evolution does not support PHP 8.x and, thus, is unable to access your database.
