### ISSUE TITLE
not working working with php 8.

### ISSUE THREAD

**Issue by bob0bob** [b2evolution/b2evolution#122]
When trying to use php 8, I get the following error.  The backend appears to work, for what I use it does.  The front end if completely broke.

Fatal error: Uncaught Error: Object of class WidgetContainer could not be converted to string in /home/mysticland/public_html/arx/inc/skins/_skin.funcs.php:3198 Stack trace: #0 /home/mysticland/public_html/arx/inc/skins/_skin.funcs.php(3198): str_replace('$wico_class$', 'evo_container__...', Array) #1 /home/mysticland/public_html/arx/inc/skins/model/_skin.class.php(440): widget_container_customize_params(Array, 'right_navigatio...', 'Right Navigatio...') #2 /home/mysticland/public_html/arx/inc/skins/_skin.funcs.php(3092): Skin->container('Right Navigatio...', Array, 'right_navigatio...') #3 /home/mysticland/public_html/arx/skins/bootstrap_site_dropdown_skin/_site_body_header.inc.php(190): widget_container('right_navigatio...', Array) #4 /home/mysticland/public_html/arx/inc/skins/_skin.funcs.php(2469): require('/home/mysticlan...') #5 /home/mysticland/public_html/arx/skins/bootstrap_blog_skin/index.main.php(36): siteskin_include('_site_body_head...') #6 /home/mysticland/public_html/arx/inc/_blog_main.inc.php(1203): require('/home/mysticlan...') #7 /home/mysticland/public_html/arx/index.php(74): require('/home/mysticlan...') #8 {main} thrown in /home/mysticland/public_html/arx/inc/skins/_skin.funcs.php on line 3198

**Comment by keithbowes** [comment]
There are a lot of these errors.  Each new version of PHP breaks something (I try to fix them in my fork but I gave up on upstream years ago (version 7 looked like it was going to exarcerbate the bloat that had existed for a while, so I forked version 6.9.7 in hopes to slim it down)), but I can't really fault PHP:  a lot of dubious coding practices were used and PHP was right for removing support for them (but wrong for supporting them in the first place).

**Comment by spooxe** [comment]
You can fix this with data casting in the widget class. The objects are WidgetContainer, Commentlist, ItemList and Item. Then the str_replace for $params work fine. Type cast them after the str_replace back to objects. Other solution is to to copy this objects and delete the original. After the str_replace add them back  and delete the clone. But there are a also lot of more deprecations with dynamic properties....

**Comment by fplanque** [comment]
@spooxe I invite you to fork the b2evolution repo and share all your mods. I think quite a few people would be grateful ;)

**Comment by spooxe** [comment]
@fplanque 
Hi, i forked and commited all my changes to install and run b2evolution in 8.2/8.3. Is always not 100% ready ;-)

**Comment by eglacias** [comment]
> [@spooxe](https://github.com/spooxe) I invite you to fork the b2evolution repo and share all your mods. I think quite a few people would be grateful ;)

@fplanque Now could we get his working fork for PHP put up on the HostGator softaculous installer site?

That’s where I started using it from, and have nowhere near the technical skill to figure out how to get my own software featured there, Probably impossible for the end loser like me, even less have I ever done the learning curve of figuring out how to compile the GitHub code etc…

**Comment by eglacias** [comment]
all right i figured out how to upload and run from the install folder etc spooxe php8 fixes.
**i got it to load on php8.3 hostgator! great now i can back up my posts at least!**
on the running b2evolution
https://foundationstone.ca/b2Blog/index.php/a/
i get only:
Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home2/jrlhmute/public_html/foundationstone.ca/b2Blog/plugins/markdown_plugin/_parsedown_extra.inc.php on line 314


on the server side /install upgrade (i had 7.2.3 spooxe was 7.2.5) got through except a line about plugin upgrade likely not important:

Letting plugins upgrade themselves...
Reloading installed plugins to make sure their config is up to date...

Deprecated: Creation of dynamic property Plugins_admin::$log_register is deprecated in /home2/jrlhmute/public_html/foundationstone.ca/b2Blog/install/_functions_evoupgrade.php on line 13132


**but a database error similar to the one that shows on front pages:**


Double checking DB structure...
Starting to check DB...

Deprecated: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /home2/jrlhmute/public_html/foundationstone.ca/b2Blog/inc/_core/model/db/_upgrade.funcs.php on line 423

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /home2/jrlhmute/public_html/foundationstone.ca/b2Blog/inc/_core/model/db/_upgrade.funcs.php on line 443
Changing default charset of DB...
Altering table «evo7b_groups»...

    Changed type of evo7b_groups.grp_ID from int unsigned to grp_ID int(10) UNSIGNED NOT NULL auto_increment, DROP PRIMARY KEY
    An unexpected error has occurred!

    If this error persists, please report it to the administrator.

    [Go back to home page](https://foundationstone.ca/b2Blog/)
    Additional information about this error:

    MySQL error!

    Incorrect table definition; there can be only one auto column and it must be defined as a key(Errno=1075)

    Your query:
ALTER TABLE evo7b_groups CHANGE COLUMN grp_ID grp_ID                           int(10) UNSIGNED NOT NULL auto_increment, DROP PRIMARY KEY

**Comment by eglacias** [comment]
so far i just followed @nanahuatl advice who had tried to fix stuff, and all seems to work:

to not display the warnings -- which had beginning to plague b2evolution 7.2.5 since PHP 7.4 -- you should make sure to modify your conf/_advanced.php file and change the value, at line no. 49, from:
$display_errors_on_production = true;
to
$display_errors_on_production = false;

**Comment by spooxe** [comment]
Nice to see that you can use it 👍 
Will commit my last changes the days

**Comment by eglacias** [comment]
That’s great, hopefully some of the errors I listed there will help you patch a few more things for PHP8 :-)
Let me know when you commit more tweaks to it, and I will post, but you should certainly post this for all of these B2evolution users, it’s a pretty big deal!

If I relearn my programming skills from my university days this year, maybe I can be part of maintaining this new fork of it, I think it’s one of the best content management system there is
